plots:
- mace_mp_0_PhaseDiagram_results:
    x:
      nodes/mace_mp/0/PhaseDiagram/results.csv: data_id
    y:
      nodes/mace_mp/0/PhaseDiagram/results.csv: formation_energy
- sevennet_0_PhaseDiagram_results:
    x:
      nodes/sevennet/0/PhaseDiagram/results.csv: data_id
    y:
      nodes/sevennet/0/PhaseDiagram/results.csv: formation_energy
- orb_v2_0_PhaseDiagram_results:
    x:
      nodes/orb_v2/0/PhaseDiagram/results.csv: data_id
    y:
      nodes/orb_v2/0/PhaseDiagram/results.csv: formation_energy
- chgnet_0_PhaseDiagram_results:
    x:
      nodes/chgnet/0/PhaseDiagram/results.csv: data_id
    y:
      nodes/chgnet/0/PhaseDiagram/results.csv: formation_energy
stages:
  chgnet_0_PhaseDiagram:
    cmd: zntrack run mlipx.nodes.phase_diagram.PhaseDiagram --name chgnet_0_PhaseDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/chgnet/0/PhaseDiagram/node-meta.json:
        cache: false
    outs:
    - nodes/chgnet/0/PhaseDiagram/frames.xyz
    - nodes/chgnet/0/PhaseDiagram/phase_diagram.json
    - nodes/chgnet/0/PhaseDiagram/results.csv
    params:
    - chgnet_0_PhaseDiagram
  initialize_MPRester:
    cmd: zntrack run mlipx.nodes.mp_api.MPRester --name initialize_MPRester
    metrics:
    - nodes/initialize/MPRester/node-meta.json:
        cache: false
    outs:
    - nodes/initialize/MPRester/frames.xyz
    params:
    - initialize_MPRester
  mace_mp_0_PhaseDiagram:
    cmd: zntrack run mlipx.nodes.phase_diagram.PhaseDiagram --name mace_mp_0_PhaseDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/mace_mp/0/PhaseDiagram/node-meta.json:
        cache: false
    outs:
    - nodes/mace_mp/0/PhaseDiagram/frames.xyz
    - nodes/mace_mp/0/PhaseDiagram/phase_diagram.json
    - nodes/mace_mp/0/PhaseDiagram/results.csv
    params:
    - mace_mp_0_PhaseDiagram
  orb_v2_0_PhaseDiagram:
    cmd: zntrack run mlipx.nodes.phase_diagram.PhaseDiagram --name orb_v2_0_PhaseDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/orb_v2/0/PhaseDiagram/node-meta.json:
        cache: false
    outs:
    - nodes/orb_v2/0/PhaseDiagram/frames.xyz
    - nodes/orb_v2/0/PhaseDiagram/phase_diagram.json
    - nodes/orb_v2/0/PhaseDiagram/results.csv
    params:
    - orb_v2_0_PhaseDiagram
  sevennet_0_PhaseDiagram:
    cmd: zntrack run mlipx.nodes.phase_diagram.PhaseDiagram --name sevennet_0_PhaseDiagram
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/sevennet/0/PhaseDiagram/node-meta.json:
        cache: false
    outs:
    - nodes/sevennet/0/PhaseDiagram/frames.xyz
    - nodes/sevennet/0/PhaseDiagram/phase_diagram.json
    - nodes/sevennet/0/PhaseDiagram/results.csv
    params:
    - sevennet_0_PhaseDiagram
