initialize_Smiles2Conformers:
  max_attempts: 1000
  num_confs: 1
  random_seed: 42
  smiles: '[Li+].[Cl-]'
mace_mp_HomonuclearDiatomics:
  elements: []
  eq_distance: covalent-radiuis
  max_distance: 2.0
  min_distance: 0.5
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: medium
    module: mace.calculators
  n_points: 100
mattersim_HomonuclearDiatomics:
  elements: []
  eq_distance: covalent-radiuis
  max_distance: 2.0
  min_distance: 0.5
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MatterSimCalculator
    device: auto
    kwargs: null
    module: mattersim.forcefield
  n_points: 100
orb_v2_HomonuclearDiatomics:
  elements: []
  eq_distance: covalent-radiuis
  max_distance: 2.0
  min_distance: 0.5
  model:
    _cls: models.OrbCalc
    device: auto
    name: orb_v2
  n_points: 100
sevennet_HomonuclearDiatomics:
  elements: []
  eq_distance: covalent-radiuis
  max_distance: 2.0
  min_distance: 0.5
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  n_points: 100
